version: "3"

services:

    auth:
        container_name: auth
        image: cristian25/authservice:latest
        build:
            context: ./Microservices/AuthService
            dockerfile: ./AuthService/Dockerfile
        ports:
            - "8080:80"  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Staging
        restart: on-failure
        volumes:
            - ./Microservices/.aspnet/auth/DataProtection-Keys:/root/.aspnet/auth/DataProtection-Keys
        networks:
            - iothub-network

    users:
        container_name: users
        image: cristian25/usersservice:latest
        build:
            context: ./Microservices/UsersService
            dockerfile: ./UsersService/Dockerfile
        ports:
            - "8081:80"  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Staging
        restart: on-failure
        volumes:
            - ./Microservices/.aspnet/users/DataProtection-Keys:/root/.aspnet/users/DataProtection-Keys
        networks:
            - iothub-network
            
    devices:
        container_name: devices
        image: cristian25/devicesservice:latest
        build:
            context: ./Microservices/DevicesService
            dockerfile: ./DevicesService/Dockerfile
        ports:
            - "8082:80"  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Staging
        restart: on-failure
        volumes:
            - ./Microservices/.aspnet/devices/DataProtection-Keys:/root/.aspnet/devices/DataProtection-Keys
        networks:
            - iothub-network
            
    notifications:
        container_name: notifications
        image: cristian25/notificationsservice:latest
        build:
            context: ./Microservices/NotificationService
            dockerfile: ./NotificationService/Dockerfile
        ports:
            - "8083:80"  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Staging
        restart: on-failure
        volumes:
            - ./Microservices/.aspnet/notifications/DataProtection-Keys:/root/.aspnet/notifications/DataProtection-Keys
        networks:
            - iothub-network
            
    statistics:
        container_name: statistics
        image: cristian25/statisticsservice:latest
        build:
            context: ./Microservices/StatisticsService
            dockerfile: ./StatisticsService/Dockerfile
        ports:
            - "8085:80"  
        environment: 
            - ASPNETCORE_ENVIRONMENT=Staging
        restart: on-failure
        volumes:
            - ./Microservices/.aspnet/statistics/DataProtection-Keys:/root/.aspnet/statistics/DataProtection-Keys
        networks:
            - iothub-network
            
    frontend:
        container_name: frontend
        image: cristian25/frontendapp:latest
        build:
            context: ./WebSinglePageAngularApp/
            dockerfile: ./Dockerfile.linux.staging
        ports:
            - "4200:80"  
        restart: on-failure
        networks:
            - iothub-network
        
networks:
    iothub-network: