#stage 1
FROM node:latest as node
WORKDIR usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build-dev

#stage 2
FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY /dist/IoTHubSPA /usr/share/nginx/html

# Expose port 80
EXPOSE 80