version: "3"

services:

    auth:
        container_name: auth
        image: cristian25/authservice:1.0
        build:
            context: ./AuthService
            dockerfile: ./AuthService/Dockerfile
        ports:
            - "8080:80"  
        restart: on-failure
        volumes:
            - ./.aspnet/auth/DataProtection-Keys:/root/.aspnet/auth/DataProtection-Keys
        networks:
            - iothub-network

    users:
        container_name: users
        image: cristian25/usersservice:1.0
        build:
            context: ./UsersService
            dockerfile: ./UsersService/Dockerfile
        ports:
            - "8081:80"  
        restart: on-failure
        volumes:
            - ./.aspnet/users/DataProtection-Keys:/root/.aspnet/users/DataProtection-Keys
        networks:
            - iothub-network
            
    devices:
        container_name: devices
        image: cristian25/devicesservice:1.0
        build:
            context: ./DevicesService
            dockerfile: ./DevicesService/Dockerfile
        ports:
            - "8082:80"  
        restart: on-failure
        volumes:
            - ./.aspnet/devices/DataProtection-Keys:/root/.aspnet/devices/DataProtection-Keys
        networks:
            - iothub-network
            
    notifications:
        container_name: notifications
        image: cristian25/notificationsservice:1.0
        build:
            context: ./NotificationService
            dockerfile: ./NotificationService/Dockerfile
        ports:
            - "8083:80"  
        restart: on-failure
        volumes:
            - ./.aspnet/notifications/DataProtection-Keys:/root/.aspnet/notifications/DataProtection-Keys
        networks:
            - iothub-network
            
    statistics:
        container_name: statistics
        image: cristian25/statisticsservice:1.0
        build:
            context: ./StatisticsService
            dockerfile: ./StatisticsService/Dockerfile
        ports:
            - "8085:80"  
        restart: on-failure
        volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/statistics/DataProtection-Keys
        networks:
            - iothub-network
        
networks:
    iothub-network: