name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Start dependencies (docker-compose)
        run: |
          docker-compose up -d  
        working-directory: ./Microservices

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
    
      - name: Restore NuGet packages
        run: dotnet restore
        working-directory: ./Microservices
        
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: ./Microservices
